### ISSUE TITLE
Best practices for configuration files

### ISSUE THREAD

**Issue by atomr3** [RobMor/NetZero#2]
Standard practices for configuration files would suggest that JSON is not the best option. While it is an excellent transmission schema, industry standard seems to lean towards YAML or other property files.

Reasons:

* Low Signal to Noise ratio
	* There is a lot of unnecessary punctuation, redundant quotations and useless curly brackets for configuration management.
	* JSON also does not support trailing commas
* Long Strings
	* No support for multi-line strings
	* Strings that carries over onto another line of the file are not possible
* Numbers
	* As defined in the JSON spec, numbers are arbitrary precision finite floating point numbers in decimal notation. If you need to use hexadecimal notation or represent values like infinity or NaN, you might be out of luck

Suggestions: `YAML`, `TOML`, `Dhall` or any custom format implementation

Sources: 
[https://revelry.co/json-configuration-file-format/](https://revelry.co/json-configuration-file-format/)
[https://softwareengineering.stackexchange.com/questions/351126/how-bad-of-an-idea-is-it-to-use-python-files-as-configuration-files](https://softwareengineering.stackexchange.com/questions/351126/how-bad-of-an-idea-is-it-to-use-python-files-as-configuration-files)
[https://arp242.net/json-config.html](https://arp242.net/json-config.html)
[https://www.lucidchart.com/techblog/2018/07/16/why-json-isnt-a-good-configuration-language/](https://www.lucidchart.com/techblog/2018/07/16/why-json-isnt-a-good-configuration-language/)

**Comment by RobMor** [comment]
I agree with you on this. Another thing to add is that JSON doesn't support comments. Python has native support for INI/TOML-like configuration files in its [configparser](https://docs.python.org/3/library/configparser.html) library which might be a good option.

**Comment by atomr3** [comment]
I would urge you to lean away from INI, which while a stable format, has not changed much from its adoption years ago. TOML seems appropriate, just be wary of using `py` files for configuration as those have their own dangers
